//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitsmackGTAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cardio
    {
        public int id { get; set; }
        public int userid { get; set; }
        public System.DateTime trandate { get; set; }
        public string activity { get; set; }
        public double distance { get; set; }
        public double time { get; set; }
    }
}
