//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitsmackGTAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db322d3d94909445799f73a2ae006638c9Entities : DbContext
    {
        public db322d3d94909445799f73a2ae006638c9Entities()
            : base("name=db322d3d94909445799f73a2ae006638c9Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APIKeys> APIKeys { get; set; }
        public DbSet<Cardio> Cardio { get; set; }
        public DbSet<EventLog> EventLog { get; set; }
        public DbSet<HabitTaskHistory> HabitTaskHistory { get; set; }
        public DbSet<HabitTasks> HabitTasks { get; set; }
        public DbSet<HabitTaskTags> HabitTaskTags { get; set; }
        public DbSet<Mint> Mint { get; set; }
        public DbSet<Pedometer> Pedometer { get; set; }
        public DbSet<TimedActivities> TimedActivities { get; set; }
        public DbSet<Todos> Todos { get; set; }
        public DbSet<HabitTags> HabitTags { get; set; }
    }
}
