//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitsmackGTAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HabitTasks
    {
        public System.Guid id { get; set; }
        public string text { get; set; }
        public string attribute { get; set; }
        public Nullable<double> priority { get; set; }
        public Nullable<double> value { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<short> down { get; set; }
        public Nullable<short> up { get; set; }
        public string type { get; set; }
    }
}
