//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitsmackGTAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mint
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public string Original_Description { get; set; }
        public Nullable<float> Amount { get; set; }
        public string Transaction_Type { get; set; }
        public string Category { get; set; }
        public string Account_Name { get; set; }
        public string Labels { get; set; }
        public string Notes { get; set; }
    }
}
