USE [master]
GO

/****** Object:  Database [BSGT]    Script Date: 1/23/2014 9:26:11 PM ******/
CREATE DATABASE [BSGT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BSGT_Data', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\BSGT_Data.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'BSGT_Log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\BSGT_Log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )
GO

ALTER DATABASE [BSGT] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BSGT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BSGT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BSGT] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BSGT] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BSGT] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BSGT] SET ARITHABORT OFF 
GO

ALTER DATABASE [BSGT] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [BSGT] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [BSGT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BSGT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BSGT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BSGT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BSGT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BSGT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BSGT] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BSGT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BSGT] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BSGT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BSGT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BSGT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BSGT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BSGT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BSGT] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BSGT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BSGT] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BSGT] SET  MULTI_USER 
GO

ALTER DATABASE [BSGT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BSGT] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BSGT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BSGT] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BSGT] SET  READ_WRITE 
GO

